# Generated by Django 4.1.7 on 2023-06-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='lname',
            new_name='lastName',
        ),
    ]
